--
-- PostgreSQL database dump
--

-- Dumped from database version 15.10
-- Dumped by pg_dump version 15.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: umkm; Type: TABLE; Schema: umkm; Owner: postgres
--

CREATE TABLE umkm.umkm (
    id integer NOT NULL,
    nama character varying(100) NOT NULL,
    alamat character varying(250),
    pinggir_jalan smallint NOT NULL,
    latitude double precision,
    longitude double precision,
    location public.geometry(Point,4326),
    dekat_fasilitas character varying(250),
    rating double precision,
    jml_ulasan integer NOT NULL,
    district_id bigint NOT NULL,
    jenis_umkm_id integer NOT NULL
);


ALTER TABLE umkm.umkm OWNER TO postgres;

--
-- Name: umkm_id_seq; Type: SEQUENCE; Schema: umkm; Owner: postgres
--

ALTER TABLE umkm.umkm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME umkm.umkm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: umkm; Type: TABLE DATA; Schema: umkm; Owner: postgres
--

COPY umkm.umkm (id, nama, alamat, pinggir_jalan, latitude, longitude, location, dekat_fasilitas, rating, jml_ulasan, district_id, jenis_umkm_id) FROM stdin;
1	Baleha eat & coffee	Jl. Karet Hijau No.5. Beji Tim.. Kecamatan Beji. Kota Depok. Jawa Barat 16422	0	-6.382834	106.821297	0101000020E610000063D34A2190B45A40FD2FD7A2058819C0	Tidak Ada	4.8	186	3276061	1
2	BENING Coffee & Space	Jl. H. Amat No.1. Kukusan. Kecamatan Beji. Kota Depok. Jawa Barat 16425	0	-6.359522	106.819118	0101000020E61000002864E76D6CB45A4022C50089267019C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.8	331	3276061	1
3	Coffee Toffee Margonda	Jl. Margonda No.438. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.366569	106.834215	0101000020E61000004AB54FC763B55A40E2E82ADD5D7719C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.5	2112	3276061	1
4	Coffith Coffee & Kitchen	Jl. K.H.M. Usman No.99. RT.1/RW.6. Kukusan. Kecamatan Beji. Kota Depok. Jawa Barat 16425	1	-6.359436	106.814424	0101000020E6100000F644D7851FB45A402D05A4FD0F7019C0	Kampus / Sekolah	4.7	870	3276061	1
5	Fore Coffee Margonda	Jl. Margonda Raya No.434. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.366822	106.834286	0101000020E6100000AF601BF164B55A4031D0B52FA07719C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.8	732	3276061	1
6	Golden Black Coffee - Depok	Jl. Margonda. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.380563	106.830834	0101000020E6100000E9995E622CB55A4046459C4EB28519C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	50	3276061	1
7	Graha Coffee & Eatery	Jl. H. M. Tohir No.73. RT.01/RW.03. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	0	-6.368378	106.836084	0101000020E61000005E2D776682B55A4078431A15387919C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.8	155	3276061	1
8	Hidden Haus Space	Jl. Curug Agung No.12. Tanah Baru. Kecamatan Beji. Kota Depok. Jawa Barat 16424	0	-6.36854	106.807474	0101000020E6100000B3976DA7ADB35A404512BD8C627919C0	Kampus / Sekolah	4.6	424	3276061	1
9	Janji Jiwa Ruko Margonda Depok	Jl. Margonda No.27. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.365813	106.834344	0101000020E6100000496760E465B55A407DCEDDAE977619C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.5	249	3276061	1
10	K-Life Depok	Jl. Margonda Raya No.379. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.368744	106.834151	0101000020E61000003F3BE0BA62B55A408962F206987919C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.9	296	3276061	1
11	Kopi Djoe	Jl. Margonda No.488. Pondok Cina. Kecamatan Beji. Kota Depok (Lantai 2 Gedung M District). Jawa Barat 16424	1	-6.361857	106.833748	0101000020E6100000BF4692205CB55A408F5033A48A7219C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	1024	3276061	1
12	Kopi Kenangan - Ruko Pondok Cina Depok	Jl. Margonda Raya No.418. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.367493	106.834204	0101000020E6100000508C2C9963B55A402409C215507819C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.1	92	3276061	1
13	Kopi Konnichiwa Beji Depok	Jl. H. Amat No.16. Kukusan. Kecamatan Beji. Kota Depok. DKI Jakarta 16425	0	-6.36039	106.821964	0101000020E6100000519FE40E9BB45A40C5387F130A7119C0	Kampus / Sekolah	4.6	68	3276061	1
14	Kopi Merah Putih UI	Jl. K.H.M. Usman No. 48 RT 001/004. Kukusan. Kecamatan Beji. Kota Depok. Jawa Barat 16425	1	-6.360823	106.816673	0101000020E6100000ADA1D45E44B45A401494A2957B7119C0	Kampus / Sekolah	4.9	206	3276061	1
15	Kotak Coffee @Depok	Jl. Margonda No.488. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.361873	106.833733	0101000020E61000002426A8E15BB55A40BD38F1D58E7219C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.5	1103	3276061	1
16	MANGATA Coffee & Eatery	Jl. Bungur Raya No.20. Kukusan. Kecamatan Beji. Kota Depok. Jawa Barat 16425	0	-6.369642	106.812864	0101000020E61000002106BAF605B45A4081E9B46E837A19C0	Stasiun / Halte. Kampus / Sekolah	4.7	93	3276061	1
17	MAOI coffee	Margonda Residence. Jl. Margonda No.3A. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.363718	106.833996	0101000020E6100000AB3FC23060B55A40BADDCB7D727419C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	240	3276061	1
18	Monty's Kitchen & Coffee	Jl. Ir. H. Juanda No.46. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa Barat 16423	1	-6.377669	106.833967	0101000020E61000005EBC1FB75FB55A4023DA8EA9BB8219C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	567	3276061	1
19	Mostly Coffee and Kitchen	Jl. Taufiqurrahman No.57A. Beji Tim.. Kecamatan Beji. Kota Depok. Jawa Barat 16422	1	-6.377211	106.822969	0101000020E6100000CC272B86ABB45A400DC4B299438219C0	Stasiun / Halte. Kampus / Sekolah	4.7	460	3276061	1
20	Point Coffee	Jl. Margonda No.504. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.36054	106.833866	0101000020E6100000C4CF7F0F5EB55A407099D365317119C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	183	3276061	1
21	Privilege Coffee Aceh & Cuisine	Jl. H. Muslih No.105. RT.06/RW.02. Beji. Kecamatan Beji. Kota Depok. Jawa Barat 16421	0	-6.383337	106.815116	0101000020E6100000919C4CDC2AB45A401363997E898819C0	Kampus / Sekolah	4.6	310	3276061	1
22	Ruangnamu	RT01. Jl. Ciliwung No.10. RW.1. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa Barat 16423	1	-6.380539	106.83163	0101000020E6100000D717096D39B55A400169FF03AC8519C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.7	1183	3276061	1
23	Sebelas Tiga Puluh Coffee house	Jl. Komjen. Pol. M. Jasin. Tugu. Kecamatan Beji. Kota Depok. Jawa Barat	1	-6.355038	106.835327	0101000020E6100000D09D60FF75B55A405859DB148F6B19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.5	321	3276061	1
24	Suar Ruang Coffee Ground	Jl. H. Amat No.2. Kukusan. Kecamatan Beji. Kota Depok. Jawa Barat 16425	0	-6.359987	106.821176	0101000020E6100000A510C8258EB45A40CCF09F6EA07019C0	Kampus / Sekolah	4.7	283	3276061	1
25	Tatap Moeka Coffee and Resto - Margonda Raya Depok	Jl. Margonda No.451. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.367087	106.833887	0101000020E6100000D06394675EB55A40A2258FA7E57719C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	361	3276061	1
26	Walking Drums Margonda Depok	Jl. Margonda Raya No.426. Pondok Cina. Kecamatan Beji. Kota Depok. Jawa Barat 16424	1	-6.366996	106.834387	0101000020E6100000494DBB9866B55A40200DA7CCCD7719C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.5	2053	3276061	1
27	Moses Coffee	Jl. Pembangunan No.3. RT.03/RW.9. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa Barat 16424	0	-6.375314	106.827202	0101000020E6100000E44BA8E0F0B45A407DEC2E50528019C0	Kampus / Sekolah	4.8	184	3276061	1
28	Archipelago Coffee & Co	Jl. Bukit Sawangan Indah A6 No 08. Duren Mekar. Kec. Bojongsari. Kota Depok. Jawa Barat 16518	0	-6.417979	106.737944	0101000020E6100000E29178793AAF5A40BDA8DDAF02AC19C0	Kampus / Sekolah	4.8	66	3276011	1
29	Daun Teduh Coffee & Eatery	Jl. Durian. Duren Seribu. Kec. Bojongsari. Kota Depok. Jawa Barat 16518	0	-6.438641	106.743388	0101000020E6100000490F43AB93AF5A402BBD361B2BC119C0	Tidak Ada	4.6	154	3276011	1
30	Ethcof Coffee & Eatery	Jl. Serua Raya No.8. Serua. Kec. Bojongsari. Kota Depok. Jawa Barat 16517	1	-6.369296	106.740537	0101000020E6100000971E4DF564AF5A40AA2C0ABB287A19C0	Kampus / Sekolah. Perkantoran	5	21	3276011	1
31	Flash Coffee - Shila at Sawangan	Jl. Raya Bojongsari No.53. Bojongsari Lama. Kec. Bojongsari. Kota Depok. Jawa Barat 16517	1	-6.400823	106.745554	0101000020E6100000BAD91F28B7AF5A403DF03158719A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	322	3276011	1
32	KopiPopi Coffee & Roastery	Jl.Mawar No.5 Rt.05 rw 03 kel.Curug Kec. Bojongsari Depok. Depokk. Jawa Barat 16517	0	-6.400219	106.740603	0101000020E61000007214200A66AF5A4088F37002D39919C0	Kampus / Sekolah	4.6	215	3276011	1
33	Lampaoe Coffee	Jl. H. Sarmat No.97. RT.04/RW.03. Pd. Petir. Kec. Bojongsari. Kota Depok. Jawa Barat 16517	0	-6.37417	106.727094	0101000020E61000008AC745B588AE5A40C993A46B267F19C0	Kampus / Sekolah	4.8	223	3276011	1
34	O'Mind Coffee And Eatery	Jl. Kp. Kandang Duren Seribu No.60. Duren Seribu. Kec. Bojongsari. Kota Depok. Jawa Barat 16518	0	-6.429629	106.744205	0101000020E61000004221020EA1AF5A401AA721AAF0B719C0	Kampus / Sekolah	4.7	46	3276011	1
35	Starbucks Coffee Bojongsari	Jl. Cinangka Raya. Bojongsari Lama. Kec. Bojongsari. Kota Depok. Jawa Barat 16516	1	-6.401426	106.742521	0101000020E6100000F7E5CC7685AF5A406F0ED76A0F9B19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	586	3276011	1
36	Tabik Coffee	Duren Seribu. Kec. Bojongsari. Kota Depok. Jawa Barat 16518	1	-6.430741	106.750792	0101000020E61000004D86E3F90CB05A40732F302B14B919C0	Kampus / Sekolah	4.8	59	3276011	1
37	Toko Kopi Manusia - Sawangan	Jl. Raya Bojongsari No.8 No. Unit D7. Bojongsari Lama. Kec. Bojongsari. Kota Depok. Jawa Barat 16517	1	-6.400695	106.747276	0101000020E61000007C45B75ED3AF5A40D1AE42CA4F9A19C0	Mall / Pusat perbelanjaan. Perkantoran	4.9	85	3276011	1
38	Kopi Sama	Bojongsari Baru. Kec. Bojongsari. Kota Depok. Jawa Barat 16516	1	-6.391358	106.744208	0101000020E6100000FB5A971AA1AF5A40A41CCC26C09019C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4	294	3276011	1
39	Terapot Home Gallery & Dapur Tera	Jl. Raya Curug No.165. RT.01/RW.05. Curug. Kec. Bojongsari. Kota Depok. Jawa Barat 16517	1	-6.397379	106.733099	0101000020E6100000BD6E1118EBAE5A40FF774485EA9619C0	Tidak Ada	4.5	291	3276011	1
40	Janji Jiwa Armeni Jilid 145	Jl. Raya Muchtar Blok Armeni No.3. RT.1/RW.5. Bojongsari Lama. Kec. Bojongsari. Kota Depok. Jawa Barat 16516	1	-6.405058	106.74643	0101000020E610000036B05582C5AF5A40C4EE3B86C79E19C0	Kampus / Sekolah. Perkantoran	4.4	228	3276011	1
41	Kopi Kenangan - Bojongsari Sawangan	Jl. Raya Bojongsari No.30 3. RW.4. Bojongsari Lama. Kec. Bojongsari. Kota Depok. Jawa Barat 16516	1	-6.403435	106.741899	0101000020E6100000D97BF1457BAF5A403E3F8C101E9D19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.4	125	3276011	1
42	ALASSé point	Jl. H. Dimun Raya No.49. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	1	-6.418333	106.848154	0101000020E61000002EFEB62748B65A40AB59677C5FAC19C0	Kampus / Sekolah. Perkantoran	4.5	317	3276031	1
43	Coffee Ember Indie Roastery	Jl. Kp. Sida Mukti. RT.03 / Rw024. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16475	0	-6.410454	106.848874	0101000020E61000002E1B9DF353B65A40AE0CAA0D4EA419C0	Kampus / Sekolah	5	8	3276031	1
44	Edisan Coffee Villa Pertiwi	Blok E5. Jl. Villa Pertiwi. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	0	-6.418894	106.852985	0101000020E6100000A1BE654E97B65A4066F6798CF2AC19C0	Kampus / Sekolah. Perkantoran	4.6	297	3276031	1
45	Jaaflo Kaffe Depok	Jl. Raya Jakarta-Bogor No.Km.35. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16431	1	-6.405449	106.861909	0101000020E610000032C85D8429B75A409BC8CC052E9F19C0	Kampus / Sekolah. Perkantoran	4.7	117	3276031	1
46	Kedai Babeh. Cilodong	Jl. Komp. Villa Pertiwi. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	1	-6.419417	106.853361	0101000020E6100000A4AB74779DB65A40B58B69A67BAD19C0	Tidak Ada	4.7	290	3276031	1
47	Kedai Koma by Koffie Made	Jl. Raya Abdul Gani. Kalibaru. Kec. Cilodong. Kota Depok. Jawa Barat 16413	1	-6.440106	106.839953	0101000020E6100000554B3ACAC1B55A40F017B325ABC219C0	Kampus / Sekolah	4.9	109	3276031	1
48	Kopi dari Hati Cilodong	HR5V+H27. Jl. Raya Abdul Gani. Kalibaru. Kec. Cilodong. Kota Depok. Jawa Barat	1	-6.441008	106.842869	0101000020E6100000FB73D190F1B55A40F418E59997C319C0	Kampus / Sekolah. Perkantoran	4.8	28	3276031	1
49	Semusim Coffee & Eatery	HR49+CRH. Jl. Raya Kalimulya. Kalimulya. Kec. Cilodong. Kota Depok. Jawa Barat 16413	1	-6.443794	106.819582	0101000020E6100000FA980F0874B45A40E3A430EF71C619C0	Kampus / Sekolah. Perkantoran	4.7	312	3276031	1
50	Tadi Pagi Coffee & Roastery ® (HQ)	Sebrang Taspen. Ruko Tran Depok Cyber. Jl. Raya Kalimulya No.7. Kalimulya. Kec. Cilodong. Kota Depok. Jawa Barat 16413	1	-6.426028	106.822795	0101000020E6100000FD135CACA8B45A409DB81CAF40B419C0	Perkantoran	4.9	374	3276031	1
51	TOMORO COFFEE - Raya Bogor Sukamaju	Jalan Raya Jakarta - Bogor. Blok Gg. Pos No.17A. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	1	-6.415711	106.85898	0101000020E6100000C2FA3F87F9B65A408E59F624B0A919C0	Kampus / Sekolah. Perkantoran	4.8	142	3276031	1
52	Transitory coffee	Jl. Tole Iskandar No.9A. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	1	-6.408419	106.853816	0101000020E61000004C33DDEBA4B65A409642209738A219C0	Tidak Ada	4.7	303	3276031	1
53	Maji Cafe	Jl. Jati Raya No.7-30. Sukamaju. Kec. Cilodong. Kota Depok. Jawa Barat 16415	0	-6.403807	106.853359	0101000020E6100000D32F116F9DB65A405F950B957F9D19C0	Tidak Ada	4.6	90	3276031	1
54	Five Coffee Forest	Jl. Raya Kp. Sawah. Jatimulya. Kec. Cilodong. Kota Depok. Jawa Barat 16413	0	-6.455374	106.826668	0101000020E61000009529E620E8B45A4079CBD58F4DD219C0	Stasiun / Halte. Kampus / Sekolah. Perkantoran	4.5	203	3276031	1
55	Ouwie Coffee And Eatery	Jl. Boulevard Grand Depok City Grand No.16. Jatimulya. Kec. Cilodong. Kota Depok. Jawa Barat 16412	1	-6.443517	106.828967	0101000020E6100000A69D9ACB0DB55A4050E1085229C619C0	Kampus / Sekolah. Perkantoran	4.6	650	3276031	1
56	One Only Coffee	Jl. Boulevard Grand Depok City No.17. Kalibaru. Kec. Cilodong. Kota Depok. Jawa Barat 16414	1	-6.434339	106.82562	0101000020E61000001BBB44F5D6B45A406682E15CC3BC19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	108	3276031	1
57	SEMBAGI	Jl. Kemang Raya No.140. RT.04/RW.05. Kalibaru. Kec. Cilodong. Kota Depok. Jawa Barat 16414	1	-6.428913	106.836178	0101000020E61000009FE8BAF083B55A4026512FF834B719C0	Kampus / Sekolah. Perkantoran	4.7	75	3276031	1
58	Bro Mind Cafe	Ruko Tran Depok Cyber Village. Jl. Raya Kalimulya No. R26. Kalimulya. Cilodong. Depok City. West Java 16413	1	-6.425374	106.822655	0101000020E610000004392861A6B45A405A46EA3D95B319C0	Kampus / Sekolah	4.6	353	3276031	1
59	Acses cafe&Rawon sengkel	Jl. Akses UI No.43. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354883	106.840381	0101000020E610000081CB63CDC8B55A401FA0FB72666B19C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.6	116	3276040	1
60	Cafe Kara	Jl. Tugu Raya No.14. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.35937	106.848675	0101000020E6100000B37BF2B050B65A4072A774B0FE6F19C0	Kampus / Sekolah	4.8	58	3276040	1
61	COTTI COFFEE - Kelapa Dua Depok	Jl. Akses UI No.60. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354864	106.84031	0101000020E61000001D2098A3C7B55A40691CEA77616B19C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.3	79	3276040	1
62	Dande’s Coffee & Eatery	Jl. Putri Tunggal No.39. Harjamukti. Kec. Cimanggis. Kota Depok. Jawa Barat 16454	1	-6.382326	106.885733	0101000020E61000003BFF76D9AFB85A4059A48977808719C0	Tidak Ada	4.8	852	3276040	1
63	Fore Coffee - Alternatif Cibubur	Jl. Alternatif Cibubur No.9. RW.8. Harjamukti. Kec. Cimanggis. Kota Depok. Jawa Barat 16454	1	-6.375895	106.898806	0101000020E6100000B5DC990986B95A4070EB6E9EEA8019C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	645	3276040	1
64	Gahari Coffee	Jl. Tugu Raya No.1. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16541	1	-6.35711	106.848232	0101000020E6100000ECDADE6E49B65A40594C6C3EAE6D19C0	Mall / Pusat perbelanjaan	4.9	129	3276040	1
65	Hidden Haus Coffee & Tea	Jl. Bukit Cengkeh 2 No.9 Blok F.1. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.362457	106.854548	0101000020E61000002E3718EAB0B65A4039D384ED277319C0	Tidak Ada	4.7	832	3276040	1
66	Irimi Coffee and Eatery	Jl. Perindustrian No.79 Blok B. Tugu. Cimanggis. Depok City. West Java 16451	1	-6.372268	106.844093	0101000020E61000001572A59E05B65A40AA6395D2337D19C0	Tidak Ada	4.5	33	3276040	1
67	Kamaie Coffee & Eatery	Jl. Nusantara No.1 B. RT.3/RW.07. Pasir Gn. Sel.. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	0	-6.348055	106.842377	0101000020E6100000C4793881E9B55A404DD6A887686419C0	Kampus / Sekolah	4.4	251	3276040	1
68	KEKO Coffee & Eatery	Jl. Bukit Pala 2 No.9 Blok B8. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	0	-6.36497	106.854191	0101000020E61000006762BA10ABB65A40A01518B2BA7519C0	Tidak Ada	5	45	3276040	1
69	Kevcall Coffee and Bakery	Jl. Komjen. Pol. M. Jasin. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16421	1	-6.353851	106.837338	0101000020E6100000AD6C1FF296B55A40A9A0A2EA576A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.4	466	3276040	1
70	Kopi Calf Kelapa Dua Depok	Jl. Komjen. Pol. M. Jasin No.16. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16951	1	-6.355048	106.851222	0101000020E6100000B0E8D66B7AB65A40740AF2B3916B19C0	Stasiun / Halte. Kampus / Sekolah	4.7	151	3276040	1
71	Kopi KongDjie Brimob	Komp. Asrama Brimob. Satu gedung dengan koperasi teratai mandiri. Jl. Akses UI Jl. Klp. Dua Raya. Pasir Gn. Sel.. Kec. Cimanggis. Kota Depok. Jawa Barat 16951	1	-6.354738	106.848713	0101000020E61000002AAC545051B65A4003983270406B19C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.4	15	3276040	1
72	Kopi Mandatory	Jl. Akses UI No.69 A. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354458	106.839454	0101000020E6100000C51F459DB9B55A40E738B709F76A19C0	Kampus / Sekolah	5	25	3276040	1
73	Krema coffee	Jl sadar no.53 rt.8/10. Kota Depok. Jawa Barat 16451	0	-6.361585	106.841714	0101000020E610000076A565A4DEB55A408AE59656437219C0	Kampus / Sekolah	5	6	3276061	1
74	Meneed Coffee	Jl. Akses UI No.8. RW.1. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.35397	106.837489	0101000020E6100000A070766B99B55A407C0F971C776A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	265	3276040	1
75	NOMA COFFEE & SPACE	Jl. Komjen. Pol. M. Jasin Jl. Klp. Dua Raya. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354411	106.836478	0101000020E6100000B47405DB88B55A40E15E99B7EA6A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	206	3276040	1
76	oemago	Jl. Lembah No.8. Pasir Gn. Sel.. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	0	-6.351941	106.840954	0101000020E61000002FDCB930D2B55A40747CB438636819C0	Kampus / Sekolah	4.8	268	3276040	1
77	oi coffee & eatery	Jl. Komjen. Pol. M. Jasin No.1. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354118	106.836798	0101000020E6100000EDD632198EB55A4020B3B3E89D6A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.8	2421	3276040	1
78	Pojok 8 Coffeeshop	Pondok Nurul Fikri. Ruko Pondok Nurul Fikri. Jl. Tugu Raya No.8. Tugu. Cimanggis. Depok City. West Java 16451	1	-6.360664	106.848649	0101000020E61000001E32E54350B65A40D06053E7517119C0	Kampus / Sekolah	4.9	87	3276040	1
79	Satu Senja Cafe	Jl. Menpor No.9a. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.35587	106.850695	0101000020E6100000BAF770C971B65A4095826E2F696C19C0	Kampus / Sekolah	4.7	158	3276040	1
80	Semoet Cafe	Jl. Radar Baru Ujung No.50-51. Pasir Gn. Sel.. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	0	-6.336494	106.84146	0101000020E610000019390B7BDAB55A406E3315E2915819C0	Tidak Ada	4.8	3617	3276040	1
81	Toko Kopi TUKU - Kelapa Dua	Jl. Akses UI No.34. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354062	106.838035	0101000020E6100000D1798D5DA2B55A4081069B3A8F6A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	835	3276040	1
82	TOMORO COFFEE - Kelapadua Depok	Ruko River View. Jl. Akses UI No.06. Tugu. Kec. Cimanggis. Kota Depok. Jawa Barat 16451	1	-6.354228	106.836627	0101000020E6100000D6FCF84B8BB55A40594FADBEBA6A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.9	1040	3276040	1
83	Analogue Coffee	Jl. Bukit Cinere Raya No.218D. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	1	-6.336227	106.790301	0101000020E6100000C03FA54A94B25A40F72004E44B5819C0	Mall / Pusat perbelanjaan. Perkantoran	4.6	313	3276061	1
84	ASMO Dine House	Jl. Bukit Cinere Raya No.6. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	1	-6.333763	106.783896	0101000020E6100000C6DD205A2BB25A409B75C6F7C55519C0	Mall / Pusat perbelanjaan. Perkantoran	4.7	828	3276061	1
85	Dekade Coffee	Jl. Jakarta No.74. Mega. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.331655	106.781876	0101000020E6100000BF61A2410AB25A4032384A5E9D5319C0	Mall / Pusat perbelanjaan	4.8	132	3276061	1
86	Escape Coffee	Jl. Cinere Raya No.10B. RT.01/RW.15. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	1	-6.343147	106.778794	0101000020E61000008C14CAC2D7B15A40CEE15AED615F19C0	Mall / Pusat perbelanjaan. Perkantoran	4.5	722	3276061	1
87	Foresthree Coffee Cinere	Komplek AL. Jl. Cinere Raya Pangkalan Jati. Kec. Cinere. Jawa Barat. Pangkalan Jati. Kec. Cinere. jakarta. Daerah Khusus Ibukota Jakarta 16513	1	-6.320877	106.783659	0101000020E6100000D40D147827B25A408527F4FA934819C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	303	3276061	1
88	GAMA. Coffee House	Jl. Sungai No.97. Pangkalan Jati Baru. Kec. Cinere. Kota Depok. Jawa Barat 16513	1	-6.325192	106.803659	0101000020E6100000B58828266FB35A40EFAEB321FF4C19C0	Tidak Ada	4.8	208	3276061	1
89	High & Low Coffee Space	Dekat PLN Gandul. Jl. Raya Gandul. Kec. Cinere. Kota Depok. Jawa Barat 16512	0	-6.338643	106.787888	0101000020E61000004B3ACAC16CB25A40CB13083BC55A19C0	Kampus / Sekolah	4.6	54	3276061	1
90	Kopitagram - Cinere	Jl. Jawa No.182 Blok H. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.347101	106.783797	0101000020E6100000FD6CE4BA29B25A40B6A2CD716E6319C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	1434	3276061	1
91	Nooka Coffee House	Jl. Bandung No.397. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.336448	106.779533	0101000020E6100000C74961DEE3B15A40EB3713D3855819C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	830	3276061	1
92	Ol' Pops Coffee Cinere	Jalan Ciloto III B2 No 17. Puri. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.324247	106.7821	0101000020E6100000E78C28ED0DB25A40F04DD367074C19C0	Mall / Pusat perbelanjaan	4.6	464	3276061	1
93	Aksara Coffee & Listening Space	Jl. Cinere Raya No.14B. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	1	-6.341548	106.778841	0101000020E61000002CF2EB87D8B15A408D0E48C2BE5D19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.8	279	3276061	1
94	Eskopi Cinere	Jl. Anggrek No.6B Blok F4. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.345782	106.78212	0101000020E61000000B630B410EB25A40902E36AD146219C0	Tidak Ada	4.9	158	3276061	1
95	Tempat Ngupi	Jl. Anggrek No.4 Blok H. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.345498	106.779011	0101000020E61000005A0EF450DBB15A4069554B3ACA6119C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	864	3276061	1
96	Kordinasi Coffee & Eatery	Jl. Kuta VI perumahan Graha. Limo. Kec. Cinere. Kota Depok. Jawa Barat 16514	0	-6.353782	106.782427	0101000020E61000007920B24813B25A4065A71FD4456A19C0	Kampus / Sekolah	4.7	864	3276061	1
97	TOMORO COFFEE - Cinere Raya	Jl. Cinere Raya No.52. Cinere. Kec. Cinere. Kota Depok. Jawa Barat 12440	1	-6.334901	106.782029	0101000020E610000082E15CC30CB25A403E97A949F05619C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.7	271	3276061	1
98	Cocote Cafe	Permata Depok Regency Blok A05/16. Ratu Jaya. Kec. Cipayung. Kota Depok. Jawa Barat 16439	1	-6.423195	106.815451	0101000020E6100000641F645930B45A40A852B3075AB119C0	Stasiun / Halte	4.6	112	3276021	1
99	Fifteenth Coffee Citayam Center Depok by Mark Design Indonesia	CITAYAM. Jl. Raya Citayam. Depok. Kec. Cipayung. Kota Depok. Jawa Barat	1	-6.429165	106.810102	0101000020E6100000261B0FB6D8B35A40F3599E0777B719C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	194	3276021	1
100	Homiya Coffee	Perumahan Jl. Green Pitara Blok F1. Cipayung. Kec. Cipayung. Kota Depok. Jawa Barat 16437	0	-6.415656	106.796332	0101000020E610000088307E1AF7B25A40728BF9B9A1A919C0	Kampus / Sekolah	5	22	3276021	1
101	Janji jiwa toast Ruko Citayam Center	HR96+W5Q. Pd. Jaya. Kec. Cipayung. Kota Depok. Jawa Barat 16436	1	-6.429737	106.810556	0101000020E6100000E7E44526E0B35A404D86E3F90CB819C0	Stasiun / Halte. Perkantoran	4.6	291	3276021	1
102	Pinanti Kopi	Jl. Raya Citayam. Pd. Jaya. Kec. Cipayung. Kota Depok. Jawa Barat 16438	1	-6.434226	106.808594	0101000020E61000007A6F0C01C0B35A40A54A94BDA5BC19C0	Stasiun / Halte. Kampus / Sekolah	4.9	154	3276021	1
103	SAE COFFEE	Jl. Pemuda Kp. Pulo Jl. Gg. Cendana. RT.03/RW.08. Cipayung Jaya. Kec. Cipayung. Kota Depok. Jawa Barat 16437	0	-6.435471	106.799956	0101000020E61000004B8FA67A32B35A40F86C1D1CECBD19C0	Tidak Ada	4.6	7	3276021	1
104	Saji Resto & Cafe	Gg. Widuri No.107. Pd. Jaya. Kec. Cipayung. Kota Depok. Jawa Barat 16438	1	-6.447766	106.80313	0101000020E6100000EF1B5F7B66B35A40FE0A992B83CA19C0	Stasiun / Halte	4.9	4392	3276021	1
105	Sosio	Ruko Anugerah. Jl. Kel Cipayung No.23. Cipayung. Kec. Cipayung. Kota Depok. Jawa Barat 16437	1	-6.421	106.796029	0101000020E6100000BA6A9E23F2B25A40C976BE9F1AAF19C0	Kampus / Sekolah	4.8	12	3276021	1
106	Foresthree Coffee Limo	No.363-367. Jl. Bukit Barisan. Limo. Kec. Limo. Kota Depok. Jawa Barat	0	-6.352069	106.776748	0101000020E6100000F04E3E3DB6B15A40E0BDA3C6846819C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.7	134	3276060	1
107	Kaizen Heritage 9.0 / Kaizen Heritage Depok Limo	Jl. Meruyung Raya No.1. Meruyung. Kec. Limo. Kota Depok. Jawa Barat 16514	1	-6.38412	106.768594	0101000020E6100000B779E3A430B15A4045F5D6C0568919C0	Kampus / Sekolah	4.7	507	3276060	1
108	Kirana Resto & Cafe	Jl. Limo Raya No.5. RT.03/RW.05. Limo. Kec. Limo. Kota Depok. Jawa Barat 16515	1	-6.353435	106.775304	0101000020E6100000501DAB949EB15A400B0C59DDEA6919C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.8	1498	3276060	1
109	Kopi Magma	Jl. Raya Krukut No.67. Krukut. Kec. Limo. Kota Depok. Jawa Barat 16514	1	-6.36287	106.79236	0101000020E610000026AAB706B6B25A404FCC7A31947319C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.8	884	3276060	1
110	Kopi Per Hari (Kopi/Hari)	Jl. Raya Krukut No.68. Krukut. Kec. Limo. Kota Depok. Jawa Barat 16512	1	-6.366016	106.793486	0101000020E61000005EF58079C8B25A403E40F7E5CC7619C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	1618	3276060	1
111	Kopi Tempat Kamu Pulang	Jl. Meruyung Raya No.69. Meruyung. Kec. Limo. Kota Depok. Jawa Barat 16514	0	-6.377093	106.768312	0101000020E6100000F54718062CB15A40BE33DAAA248219C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	224	3276060	1
112	Kopidiam	Jl. Raya Pulo Mangga. Grogol. Kec. Limo. Kota Depok. Jawa Barat	1	-6.373859	106.788636	0101000020E6100000B01C210379B25A40D542C9E4D47E19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	20	3276060	1
113	Kuru Coffee	Jl. Usman Dehir No.14. Limo. Kec. Limo. Kota Depok. Jawa Barat 16514	0	-6.369602	106.774062	0101000020E6100000E3C4573B8AB15A4010255AF2787A19C0	Kampus / Sekolah. Perkantoran	4.9	53	3276060	1
114	PARCO Coffee and Eatery	Jl. Cinere Raya No.27. Limo. Kec. Limo. Kota Depok. Jawa Barat 16515	1	-6.346278	106.776989	0101000020E610000083161230BAB15A40124C35B3966219C0	Kampus / Sekolah. Perkantoran	4.8	1109	3276060	1
115	Rumah Kopi @ Limo ( Ruko@Limo )	Jl. Limo Raya. Limo. Kec. Limo. Kota Depok. Jawa Barat 16515	1	-6.363725	106.775608	0101000020E610000006A1BC8FA3B15A404DF38E53747419C0	Kampus / Sekolah	5	61	3276060	1
116	Lokakama 27	Jl. Anggrek F2 No. 27. Kec. Limo. Kota Depok. Jawa Barat 16515	0	-6.345222	106.780231	0101000020E6100000D314014EEFB15A4058703FE0816119C0	Tidak Ada	4.4	432	3276060	1
117	Bagi Kopi Margonda Raya	Jl. Margonda No.6. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.391479	106.818997	0101000020E61000006AA164726AB45A407C48F8DEDF9019C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Perkantoran	4.7	1406	3276020	1
118	Bajawa Flores NTT Depok	Jl. Pemuda No.23 a. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.400717	106.821462	0101000020E6100000083A5AD592B45A4010CEA78E559A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.6	2291	3276020	1
119	Chanda Coffee	Jl. Puri Depok Mas No.14 Blok J. Pancoran Mas. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16436	0	-6.398466	106.802847	0101000020E6100000452C62D861B35A4091459A78079819C0	Kampus / Sekolah	4.6	152	3276020	1
120	COFFEE E&S	Jl. Mangga Raya No.96. Depok Jaya. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16432	0	-6.397003	106.813324	0101000020E610000052431B800DB45A40D2A755F4879619C0	Stasiun / Halte. Kampus / Sekolah	4.7	132	3276020	1
121	Coffee Result	8. Jl. Melati Raya No.125. RT.8/RW.5. Depok Jaya. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16432	1	-6.390334	106.813011	0101000020E610000073124A5F08B45A40451152B7B38F19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	33	3276020	1
122	Cornelis koffie	Jl. Pemuda No.16. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.402472	106.820603	0101000020E6100000F8FF71C284B45A400D39B69E219C19C0	Stasiun / Halte. Kampus / Sekolah	4.6	611	3276020	1
123	Dadi's Coffee Garden	Jl. Siliwangi No.7. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16436	1	-6.399558	106.82216	0101000020E61000001405FA449EB45A40B16B7BBB259919C0	Stasiun / Halte. Kampus / Sekolah. Perkantoran	4.5	1522	3276020	1
124	Dklakon cafe	Ruko Pasar Segar Blok RC1 No. 1-3. Jl. Tole Iskandar. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.403557	106.833966	0101000020E610000076FEEDB25FB55A409949D40B3E9D19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	77	3276020	1
125	Emily Listening Space	Jl. Jambu No.2. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.398611	106.826709	0101000020E6100000C493DDCCE8B45A40AD4D637B2D9819C0	Stasiun / Halte. Kampus / Sekolah	4.6	489	3276020	1
126	Gens Coffee	Jl. Masjid Jl. Tiank 2 No.A6. Vertihouse. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16435	0	-6.402942	106.800666	0101000020E61000003A419B1C3EB35A4045BDE0D39C9C19C0	Kampus / Sekolah	4.9	14	3276020	1
127	Green Cozy Coffee House	Jl. Sumurbatu Raya No.165. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.399887	106.827579	0101000020E6100000CFF6E80DF7B45A40D8614CFA7B9919C0	Kampus / Sekolah	4.8	50	3276020	1
128	INTERAKSI SPACE	Jl. Margonda No.15A. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.397818	106.820824	0101000020E610000067F1626188B45A405F0A0F9A5D9719C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.5	1656	3276020	1
129	Jacob Koffie Huis	Jl. Kemuning No.1. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.399992	106.81981	0101000020E6100000C3BB5CC477B45A4083A5BA80979919C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	1911	3276020	1
130	Kelingan Kopi	Jl. Kali Licin No.292. Pancoran Mas. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16433	1	-6.400507	106.796942	0101000020E6100000C4B3041901B35A40BB46CB811E9A19C0	Kampus / Sekolah	4.8	152	3276020	1
131	Kopi Nako Depok	Jl. Margonda No.38. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.396495	106.820505	0101000020E6100000164D672783B45A402E1C08C9029619C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Perkantoran	4.7	7900	3276020	1
132	KOPI OMDON	Jl. Cempaka No.1A. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.399178	106.823424	0101000020E610000075AF93FAB2B45A4079211D1EC29819C0	Kampus / Sekolah	4.7	156	3276020	1
133	Koti	JR47+PR9. Jl. Nusantara Raya No.282. Depok Jaya. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16432	1	-6.394338	106.81434	0101000020E6100000C7F484251EB45A40BB473657CD9319C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.6	716	3276020	1
134	LOOPLINE COFFEE DEPOK	Jl. Dewi Sartika No.6. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.399558	106.818798	0101000020E6100000EF01BA2F67B45A40B16B7BBB259919C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	169	3276020	1
135	LOUIS CAFE	Jl. Mawar No.22. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	0	-6.400647	106.82467	0101000020E610000082FFAD64C7B45A4049F60835439A19C0	Stasiun / Halte. Kampus / Sekolah	4.6	1900	3276020	1
136	Meet Up Cafe	Jl. Raya Sawangan No.19. Pancoran Mas. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16436	1	-6.397589	106.810366	0101000020E610000095F25A09DDB35A4054FF2092219719C0	Stasiun / Halte. Kampus / Sekolah	4.4	1597	3276020	1
137	PHiL & CO - Coffee Shop - Stasiun Depok Lama - Working Space	Jl. Stasiun Depok Lama. Ruko Jl. Kartini No.3. Kota Depok. Jawa Barat 16431	1	-6.405502	106.818447	0101000020E610000099A0866F61B45A40B2D991EA3B9F19C0	Stasiun / Halte. Perkantoran	4.7	453	3276061	1
138	Sobat Simpur	Boulevard Grand Depok City. Pancoran Mas Avenue Tenant 4. Depok City. West Java 16431	1	-6.410473	106.817806	0101000020E61000003F1EFAEE56B45A406490BB0853A419C0	Stasiun / Halte. Perkantoran	4.9	206	3276020	1
139	Tanabaru Kopi	Jl. Swadaya VIII. Pancoran MAS. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16436. Kota Depok. Jawa Barat 16513	0	-6.390366	106.804317	0101000020E61000007AA702EE79B35A40A0E1CD1ABC8F19C0	Kampus / Sekolah	5	125	3276020	1
140	Warkocag Aesthetic	Gg. Situ Pancoran Mas Jl. Raya Cagar Alam No.16. RT.05/RW.18. Pancoran Mas. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16436	0	-6.404614	106.810729	0101000020E6100000CD3AE3FBE2B35A40D503E621539E19C0	Stasiun / Halte	4.8	104	3276020	1
141	Kopi Calf To Go Depok Beji	Jl. Arif Rahman Hakim No.4. Depok Jaya. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16432	1	-6.388811	106.814551	0101000020E6100000247B849A21B45A40DB4C8578248E19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	216	3276020	1
142	The Gade Coffee & Gold Depok	Jl. Siliwangi No.20. Depok. Kec. Pancoran Mas. Kota Depok. Jawa Barat 16431	1	-6.399364	106.822481	0101000020E610000035255987A3B45A408ACC5CE0F29819C0	Stasiun / Halte. Kampus / Sekolah. Perkantoran	4.7	648	3276020	1
143	5cm Coffe and Eatery (Cabang Depok)	Jl. Raya Muchtar No.Pusara. Bojongsari Lama. Kec. Sawangan. Kota Depok. Jawa Barat	1	-6.407357	106.755681	0101000020E6100000594DD7135DB05A40CB2F833122A119C0	Kampus / Sekolah	4.7	246	3276011	1
144	Atatu Kopi @Sawanganbaru	Jl. Jati No.75. Sawangan Baru. Kec. Sawangan. Kota Depok. Jawa Barat 16511	0	-6.399131	106.765612	0101000020E6100000365B79C9FFB05A407347FFCBB59819C0	Tidak Ada	4.6	214	3276061	1
145	Avenue Coffee and Eatery	Ruko Shila D5 No.11. Bojongsari Lama. Kec. Sawangan. Kota Depok. Jawa Barat 16516	1	-6.400619	106.745507	0101000020E61000001AFCFD62B6AF5A40F99FFCDD3B9A19C0	Mall / Pusat perbelanjaan	4.9	579	3276011	1
146	coffee in town	Jl. Raya Muchtar No.94. Sawangan. Kec. Sawangan. Kota Depok. Jawa Barat 16511	1	-6.40723	106.754606	0101000020E610000062D7F6764BB05A40E2CCAFE600A119C0	Kampus / Sekolah. Perkantoran	4.8	38	3276061	1
147	Fore Coffee - Felicity Sawangan	Ruko Felicity. Jl. Raya Parung - Ciputat No.3. Kedaung. Kec. Sawangan. Kota Depok. Jawa Barat 16516	1	-6.3798	106.746606	0101000020E6100000D53F8864C8AF5A404D158C4AEA8419C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.7	76	3276061	1
148	H47 Coffee Sawangan	SHA-01. Marche Modern Market. Jl. Sawangan Raya. Sawangan. Kec. Sawangan. Kota Depok. Jawa Barat 16517	1	-6.404915	106.750452	0101000020E6100000F04DD36707B05A40ADA3AA09A29E19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah	4.9	15	3276061	1
149	Jj Cafe	Jl. Jambu. Bedahan. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.432712	106.767224	0101000020E6100000342DB1321AB15A40D658C2DA18BB19C0	Tidak Ada	4.6	235	3276061	1
150	KebunNara kopi	Jl. Batu Ampar Kekupu. RT.01/RW.08. Pasir Putih. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.435842	106.783583	0101000020E6100000E6AC4F3926B25A4097E4805D4DBE19C0	Tidak Ada	4.5	200	3276061	1
151	Kedai Kopi Kita SWG	Ruko Villa Rizki Ilhami 2 RB/8. Pengasinan. Kec. Sawangan. Kota Depok. Jawa Barat 16517	0	-6.408713	106.749428	0101000020E61000003AADDBA0F6AF5A40D9CC21A985A219C0	Kampus / Sekolah. Perkantoran	4.9	94	3276061	1
152	KICENWAWA Coffee Roastery	Bhakti Karya. Jl. Raya Muchtar. Sawangan Baru. Kec. Sawangan. Kota Depok. Jawa Barat 16511	1	-6.406651	106.754595	0101000020E610000068AED3484BB05A40F48AA71E69A019C0	Kampus / Sekolah	5	45	3276061	1
153	Kisah Rasa Kopi	ruko sawangan permai. baru. saw. Jl. Sawangan Permai No.16 blok g2 r2. Sawangan Baru. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.405667	106.775226	0101000020E61000009240834D9DB15A400744882B679F19C0	Kampus / Sekolah	5	50	3276061	1
154	KongDjie Coffee	Jl. Raihan. Pengasinan. Kec. Sawangan. Kota Depok. Jawa Barat 16518	0	-6.408489	106.749081	0101000020E610000085436FF1F0AF5A405D1ABFF04AA219C0	Kampus / Sekolah	4.6	325	3276061	1
155	Lumos Cafe Depok	Jl. Raya Pengasinan No.5. Sawangan. Kec. Sawangan. Kota Depok. Jawa Barat 16511	1	-6.409567	106.755376	0101000020E6100000BB0B941458B05A4055151A8865A319C0	Kampus / Sekolah	4.9	48	3276061	1
156	Makita Coffee Garden	Jl. Garuda Raya No.577. Pasir Putih. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.432705	106.786898	0101000020E61000006BD26D895CB25A404243FF0417BB19C0	Kampus / Sekolah	4.3	365	3276061	1
157	Ol’ Pops Coffee Cinangka	Jl. Pendidikan No.77. Cinangka. Kec. Sawangan. Kota Depok. Jawa Barat 16516	0	-6.374559	106.759054	0101000020E610000079793A5794B05A409AB0FD648C7F19C0	Kampus / Sekolah	4.5	463	3276061	1
158	Peanut Coffee Indonesia	Ruko Galeria. Jl. Raya Muchtar No.26. Sawangan Baru. Kec. Sawangan. Kota Depok. Jawa Barat 16511	1	-6.393305	106.77178	0101000020E61000003EEDF0D764B15A40C269C18BBE9219C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.7	75	3276061	1
159	Pituwolu Coffee	Jl. Abdul Wahab Gg. Nangka No.68. Sawangan. Kec. Sawangan. Kota Depok. Jawa Barat 16511	0	-6.396506	106.761521	0101000020E6100000E78D93C2BCB05A40CDAB3AAB059619C0	Kampus / Sekolah	4.7	144	3276061	1
160	Sisterhook Cafe	Perumahan Diamond Lake Side Blok Q18. Jl. Jinjing No.16. Pasir Putih. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.418495	106.775309	0101000020E6100000D8D2A3A99EB15A4078280AF489AC19C0	Tidak Ada	4.9	154	3276061	1
161	Tomoro Coffee - Raya Sawangan	Jl. Raya Muchtar No.80. Sawangan Lama. Kec. Sawangan. Kota Depok. Jawa Barat 16517	1	-6.393916	106.79464	0101000020E6100000FB05BB61DBB25A400B7C45B75E9319C0	Kampus / Sekolah. Perkantoran	4.8	213	3276061	1
162	Warung Kopi Tepi Sungai	Jl. Swadaya 1 No.71. Sawangan. Kec. Sawangan. Kota Depok. Jawa Barat 16517	0	-6.389496	106.766316	0101000020E6100000B39943520BB15A40F7B0170AD88E19C0	Tidak Ada	4.8	2128	3276061	1
163	Zona Coffee Roaster	Komp bni. Jl. H. Sulaiman No.46. Bedahan. Kec. Sawangan. Kota Depok. Jawa Barat 16519	0	-6.424121	106.765223	0101000020E610000069C9E369F9B05A40F12F82C64CB219C0	Kampus / Sekolah	4.9	68	3276061	1
164	Echo Space Coffee	Depok 2 Tengah. Jl. Calung Raya No.Kav.85. Mekar Jaya. Sukmajaya. Depok City. West Java 16411	0	-6.393272	106.839367	0101000020E6100000DD955D30B8B55A40E4BA29E5B59219C0	Kampus / Sekolah	4.8	130	3276030	1
165	Flash Coffee - Ruko Grand Depok City	Ruko Verbena. Jl. Boulevard Grand Depok City No.7. Tirtajaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16412	1	-6.412613	106.827329	0101000020E6100000138255F5F2B45A40289EB30584A619C0	Kampus / Sekolah. Perkantoran	4.8	167	3276030	1
166	HANGGAR KOPI - Cafe dan Coffee Roastery	Ruko Pesona Khayangan. Jl. K.H.M. Yusuf Raya No.10 Blok B. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	1	-6.380084	106.845937	0101000020E61000007D5EF1D423B65A4074EE76BD348519C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	498	3276030	1
167	Kopi Kenangan Pondok Duta	Jl. Raya Pd. Duta. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16951	1	-6.372364	106.852819	0101000020E6100000139A249694B65A40BBD408FD4C7D19C0	Kampus / Sekolah. Perkantoran	4.9	22	3276030	1
168	Kopi Kenangan x Chigo x Flip Burger	Jl. Tole Iskandar. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16415	1	-6.402324	106.83639	0101000020E6100000E42CEC6987B55A40689599D2FA9B19C0	Mall / Pusat perbelanjaan	4.6	332	3276030	1
169	Kopi wasa	Jl. Raden Saleh Blk. A No.4. RT.05/RW.05. Sukmajaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16412	1	-6.404278	106.845942	0101000020E61000000514EAE923B65A401AF8510DFB9D19C0	Kampus / Sekolah	4.7	186	3276030	1
170	Langikula	Gg. H. Solehan No.98. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	0	-6.37312	106.852174	0101000020E61000001920D1048AB65A4020EF552B137E19C0	Tidak Ada	4.8	105	3276030	1
171	LDG coffee & eatery	Jl. Sakub. RT.02/RW.23. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	1	-6.377562	106.848042	0101000020E61000009BE8F35146B65A4073D9E89C9F8219C0	Stasiun / Halte	4.9	101	3276030	1
172	Mq Coffee & Resto	Jl. Calung Raya No.9. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	0	-6.39322	106.846023	0101000020E61000007C2AA73D25B65A4051888043A89219C0	Kampus / Sekolah	4.9	51	3276030	1
173	SAVIO coffee and eatery	Jl. Bahagia Raya No.23 Blok AA. Abadijaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	1	-6.39657	106.851248	0101000020E61000004432E4D87AB65A40834C3272169619C0	Tidak Ada	4.6	562	3276030	1
174	Serab Coffee Brewery	Jl. Raya KSU No.97. Tirtajaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16412	1	-6.407661	106.838385	0101000020E61000003F1D8F19A8B55A402B6B9BE271A119C0	Kampus / Sekolah. Perkantoran	4.6	297	3276030	1
175	Signal Coffee Depok	Jl. Moch Nail No.54. RT.04/RW.025 kel. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	1	-6.37305	106.846039	0101000020E6100000FF08C38025B65A405917B7D1007E19C0	Mall / Pusat perbelanjaan	4.7	336	3276030	1
176	SKUY Coffee & Space	Jl. Prof. Lafran Pane. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	1	-6.371698	106.845938	0101000020E6100000651C23D923B65A4056F487669E7C19C0	Kampus / Sekolah. Perkantoran	4.4	75	3276030	1
177	Temoei Kopi	Jl. Bahagia Raya No.2. Abadijaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16412	1	-6.399608	106.854234	0101000020E6100000674815C5ABB65A403FE1ECD6329919C0	Kampus / Sekolah	4.9	230	3276030	1
178	Tentang Kopi Sukmajaya	Samping Polsek. Jl. Bahagia Raya No.4. Sukamaju. Kec. Sukmajaya. Kota Depok. Jawa Barat 16417	1	-6.402633	106.851323	0101000020E610000049D576137CB65A4056293DD34B9C19C0	Kampus / Sekolah. Perkantoran	4.5	118	3276030	1
179	TOMORO COFFEE	Jl. Sentosa Raya No.27C. RT.005/RW.010. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	1	-6.393838	106.836939	0101000020E6100000CE6F986890B55A402DB0C7444A9319C0	Tidak Ada	4.7	365	3276030	1
180	TOMORO COFFEE - Tole Iskandar	Jl. Tole Iskandar. Abadijaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16412	1	-6.405261	106.843492	0101000020E6100000029CDEC5FBB55A40856055BDFC9E19C0	Stasiun / Halte	4.9	267	3276030	1
181	Warnoes Juanda	Jl. Sakub. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	1	-6.378067	106.847796	0101000020E61000007F6B274A42B65A408EC9E2FE238319C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	815	3276030	1
182	Naqys Cafe & Bakery	Blok AH No. Jl. Pesona Kayangan Estate No.1. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	0	-6.390947	106.830008	0101000020E6100000C7DADFD91EB55A4093E00D69549019C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah	4.7	270	3276030	1
183	Batakoffie	Jl. Gama Setia Raya No.8 Blok A3. RT.7/RW.17. Bakti Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16418	0	-6.373926	106.853334	0101000020E610000027A435069DB65A40137F1475E67E19C0	Kampus / Sekolah	4.7	114	3276030	1
184	SEVENBILLION COFFEE X ROTISO	Jl. K.H.M. Yusuf Raya No.15-16. Mekar Jaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	1	-6.384227	106.839408	0101000020E61000000D0055DCB8B55A40F5F57CCD728919C0	Kampus / Sekolah. Perkantoran	4.9	282	3276030	1
185	Rileks Kafe21 Depok	Jl. Merdeka Raya Perum Griya Kencana Blok AA9. Abadijaya. Kec. Sukmajaya. Kota Depok. Jawa Barat 16411	1	-6.396365	106.849857	0101000020E6100000B5519D0E64B65A40BD1DE1B4E09519C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	90	3276030	1
186	Coffee Thinks Tapos	Jl. Cempedak Raya No.C3 No 1. RT.002/RW.012. Sukamaju Baru. Kec. Tapos. Kota Depok. Jawa Barat 16455	0	-6.384238	106.867481	0101000020E6100000B03907CF84B75A409485AFAF758919C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	49	3276041	1
187	Hilling Café Cibubur	Jl. Raya Leuwinanggung No.20. Leuwinanggung. Kec. Tapos. Kota Depok. Jawa Barat 16456	0	-6.389063	106.914092	0101000020E61000004162BB7B80BA5A40A855F487668E19C0	Kampus / Sekolah. Perkantoran	4.6	359	3276041	1
188	Kopi Kota Jaya	Cimanggis Golf Estate. ruko. Tapos. Depok City. West Java 16457	1	-6.380512	106.902732	0101000020E61000005F43705CC6B95A4035F10EF0A48519C0	Stasiun / Halte. Mall / Pusat perbelanjaan	4.8	149	3276061	1
189	Matuju Coffee & Kitchen	gubug gurame. Jl. Raya Tapos Depan Rm. Gubug gurame No.8. RT.003/RW.001. Cimpaeun. Kec. Tapos. Kota Depok. Jawa Barat 16464	1	-6.431599	106.877353	0101000020E61000000A83328D26B85A40FAF19716F5B919C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.7	281	3276041	1
190	Omah Kopi 78	Jl. Gg. Kecapi No.78. Leuwinanggung. Kec. Tapos. Kota Depok. Jawa Barat 16456	0	-6.398459	106.900082	0101000020E6100000F86D88F19AB95A40FD2FD7A2059819C0	Stasiun / Halte. Kampus / Sekolah	4.7	2201	3276041	1
191	POINT COFFEE EXIT TOL CIMANGGIS	Jl. Cimanggis Boulevard No.2. RW.11. Tapos. Kec. Tapos. Kota Depok. Jawa Barat 16457	1	-6.41717	106.891263	0101000020E6100000A148F7730AB95A40417DCB9C2EAB19C0	Mall / Pusat perbelanjaan. Perkantoran	4.7	429	3276041	1
192	Tepi Bambu	Jl. Banjaran Pucung No.5. Cilangkap. Kec. Tapos. Kota Depok. Jawa Barat 16465	0	-6.424195	106.863905	0101000020E6100000757632384AB75A40C381902C60B219C0	Kampus / Sekolah	4.6	270	3276041	1
193	TOMORO COFFEE - Tapos	Jl. Ciherang Raya No.15. Sukatani. Kec. Tapos. Kota Depok. Jawa Barat 16454	1	-6.393489	106.886908	0101000020E6100000E4A3C519C3B85A40CD57C9C7EE9219C0	Kampus / Sekolah. Perkantoran	4.7	321	3276041	1
194	Pehobi Coffee & Roastery	blok ac no. Jl. Media 2 No.2. Sukatani. Kec. Tapos. Kota Depok. Jawa Barat 16461	0	-6.387011	106.886356	0101000020E61000004227840EBAB85A40DFC4909C4C8C19C0	Tidak Ada	4.9	181	3276041	1
195	sumber coffee	Jl. Wijaya Kusuma No.pelita 1. Sukatani. Kec. Tapos. Kota Depok. Jawa Barat 16454	1	-6.395299	106.88984	0101000020E61000000DAB7823F3B85A40E690D442C99419C0	Kampus / Sekolah	4.9	36	3276041	1
196	ASTA COFFEE & BUSINESS	Jl. Raya Leuwinanggung No.999. Tapos. Kec. Tapos. Kota Depok. Jawa Barat 16457	1	-6.407364	106.903332	0101000020E61000008A5B0531D0B95A405F45460724A119C0	Tidak Ada	4.8	42	3276041	1
197	Nomnom Coffee & Resto	Jl. Raya Tapos. Tapos. Kec. Tapos. Kota Depok. Jawa Barat 16457	1	-6.436874	106.882154	0101000020E610000047020D3675B85A400DE4D9E55BBF19C0	Kampus / Sekolah	4.8	30	3276041	1
198	Wonglimo Coffee & Eatery	Jl. Akses Tol Cimanggis - Cikeas Gg. Sawo No.47. Leuwinanggung. Kec. Tapos. Kota Depok. Jawa Barat 16456	0	-6.402091	106.915218	0101000020E610000079AD84EE92BA5A4052103CBEBD9B19C0	Tidak Ada	4.5	311	3276041	1
199	Kaldera Coffee & Kitchen	Jl. Jatijajar 1. Jatijajar. Kec. Tapos. Kota Depok. Jawa Barat 16451	0	-6.421091	106.861261	0101000020E61000007F1475E61EB75A404B8FA67A32AF19C0	Tidak Ada	4.6	31	3276041	1
200	The Pine By Moksha	Jl. Caringin No.1. Rangkapan Jaya. Kota Depok	1	-6.3988255	106.7913386	0101000020E6100000FFC3A74AA5B25A404F3E3DB6659819C0	Tidak Ada	4.5	267	3276061	1
201	D'Moora Coffee	Jl. Pramuka Raya No.D4. Mampang. Kota Depok	1	-6.3857996	106.7914705	0101000020E6100000EC4FE273A7B25A40523DE30C0F8B19C0	Tidak Ada	4.9	29	3276061	1
202	Kopi Kogi X Mura Ramen	Parkiran Mobil Depan. Depok Town Center. Jl. Raya Sawangan No.1. Rangkapan Jaya. Kota Depok	1	-6.394784	106.793356	0101000020E610000077853E58C6B25A40AEEFC341429419C0	Mall / Pusat perbelanjaan. Halte	4.8	250	3276061	1
203	KopaKumi	Jl. Nusantara Raya No.50. RT.004/RW.013. Beji. Kota Depok	1	-6.3858919	106.8147402	0101000020E6100000236F14B424B45A404B2A093F278B19C0	Tidak Ada	4.8	54	3276061	1
204	Kopi Kenangan - Ruko Nusantara Depok	Ruko Nusantara. Jl. Nusantara Raya No.294. Depok Jaya. Kota Depok	1	-6.3947854	106.8142827	0101000020E6100000B68C2F351DB45A40CCC0B79F429419C0	Kampus / Sekolah	4.1	99	3276061	1
205	Help Me Coffee	Jl. Nangka Raya No.315. Depok Jaya. Kota Depok	1	-6.395588	106.8140177	0101000020E61000005EF7B1DD18B45A409CC24A05159519C0	Kampus / Sekolah	4.9	38	3276061	1
206	Toko Kopi TUKU - Pancoran Mas	Jl. Raya Sawangan No.4. Mampang. Kota Depok	1	-6.3944287	106.8016328	0101000020E6100000A8D9A8F34DB35A40496AFC1DE59319C0	Kampus / Sekolah	4.6	313	3276020	1
207	TIMURAN KOPI	Mampang RT 003/RW 06 No. 9. Mampang. Depok City	1	-6.3939662	106.7977279	0101000020E6100000D56652F90DB35A40E7EA22E06B9319C0	Tidak Ada	4.9	99	3276061	1
208	Craftsman Coffee	Jl. Anyelir 7 No.81. RT.3/RW.06. Depok Jaya. Kota Depok	0	-6.3912287	106.8147362	0101000020E610000082774DA324B45A40C1069F419E9019C0	Mall / Pusat perbelanjaan. Perkantoran	5	63	3276061	1
209	Flywheels coffee station	Jl. Raya Grogol No.40. Grogol. Kota Depok	1	-6.3829074	106.7903512	0101000020E6100000AE16331D95B25A40E795A1E0188819C0	Tidak Ada	4.8	4	3276061	1
210	Beiji Kopi	Jl. Ridwan Rais No.16. Beji. Kota Depok	1	-6.3876062	106.8202186	0101000020E61000008AA427767EB45A4047E8C2A3E88C19C0	Kampus / Sekolah	4.5	127	3276061	1
211	Dopamine Avenue	Jl. Pemuda No.32. Depok. Kota Depok	1	-6.4022756	106.8217331	0101000020E61000009BA26D4697B45A4045EA8722EE9B19C0	Kampus / Sekolah. Perkantoran	4.5	463	3276061	1
212	Waroeng SKI Kartini	Ruko Kartini. Jl. Raya Citayam No.9 Blok A. RT.001/RW.02. Depok. Kota Depok	1	-6.4056314	106.818738	0101000020E6100000847F113466B45A403BEC74D65D9F19C0	Stasiun / Halte	5	343	3276061	1
213	Bluish Cafe Bar	Jl. Margonda. Depok. Kota Depok	1	-6.3897808	106.8256995	0101000020E6100000B534B742D8B45A40536FB2B2228F19C0	Mall / Pusat perbelanjaan	4.9	197	3276061	1
214	JOY Café Garden	Jl. Nusantara Raya No.31. Depok Jaya. Kota Depok	1	-6.3915679	106.8144185	0101000020E610000079B0C56E1FB45A4052A7F22CF79019C0	Mall / Pusat perbelanjaan. Perkantoran	4.7	113	3276061	1
215	Sekata Kopi	Jl. Siliwangi No.40. Depok. Kota Depok	1	-6.3996585	106.8240103	0101000020E61000004C84B295BCB45A400F46EC13409919C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	50	3276061	1
216	Kedai Tekoo	Jl. H. Kani No.48. RT.005/RW.13. Beji. Kota Depok	0	-6.38811	106.8162454	0101000020E6100000ABA0585D3DB45A40930035B56C8D19C0	Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	5	3	3276061	1
217	Point Coffee fresh Siliwangi depok	Jl. Siliwangi No.58. Depok. Kota Depok	1	-6.3999773	106.8256048	0101000020E6100000EBDA83B5D6B45A40CC913AA6939919C0	Kampus / Sekolah. Perkantoran	4.1	27	3276061	1
218	Anomali Coffee & Kitchen - MARGOCITY	Margocity. G Jl. Margonda Raya No.358. Kemiri Muka. Kota Depok	1	-6.3740062	106.8342428	0101000020E61000001ABBE93B64B55A404401367BFB7E19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	153	3276061	1
219	Somewhere Goods Coffee	Jl. Mandor Basyir I No.15. Kukusan. Kota Depok	1	-6.370644	106.8149256	0101000020E6100000152BB4BD27B45A40A2D5C9198A7B19C0	Kampus / Sekolah	4.9	58	3276061	1
220	THINK CAFE by Prashanda's House	Jl. Ketapang No.8. RT.03/RW.09. Pondok Cina. Kota Depok	0	-6.3758112	106.8274691	0101000020E6100000D6BCF440F5B45A40CFE1B5A6D48019C0	Kampus / Sekolah	4.9	204	3276061	1
221	koba coffee and eat. Kukusan Beji Kota Depok	jln kh usman No.191. Kukusan. Kota Depok	1	-6.3734032	106.8133959	0101000020E6100000D54CADAD0EB45A4012E390685D7E19C0	Mall / Pusat perbelanjaan. Perkantoran	4.5	160	3276061	1
222	Bertumbuh Coffee	Jl. Legong Blk. 1 No.44. Mekar Jaya. Kota Depok	0	-6.3958017	106.8341367	0101000020E61000002DB9E57E62B55A4008CE740A4D9519C0	Tidak ada	5	13	3276061	1
223	Indorep Internet Cafe And Coffee Shop	Jl. Margonda No.386. Kemiri Muka. Kota Depok	1	-6.3699662	106.8338312	0101000020E61000009B98897D5DB55A406880666BD87A19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.9	71	3276061	1
224	Djournal Coffee - Margo City	Area Old House. Jl. Margonda No.358 Lower Ground. Kemiri Muka. Kota Depok	1	-6.3731044	106.8349841	0101000020E6100000858B266170B55A408DF96F140F7E19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.8	837	3276061	1
225	TOMORO COFFEE - DMall Depok	DMall Depok. Jl. Margonda No.36. Depok. Depok City	1	-6.3869257	106.8268249	0101000020E61000002F41FCB2EAB45A4079ED2D40368C19C0	Mall / Pusat perbelanjaan. Perkantoran	4.7	158	3276061	1
226	Tomoro Coffee - Margonda Raya	Jl. Margonda.243b. RT.01/RW.12. Kemiri Muka. Kecamatan Beji. Kota Depok. Jawa BaratDepok. Jawa Barat	1	-6.3819552	106.8298269	0101000020E6100000D43549E21BB55A40082692431F8719C0	Mall / Pusat perbelanjaan. Perkantoran	4.9	412	3276061	1
227	Green Coffee House	Jl. Sumurbatu Raya No.165. Depok. Kota Depok	0	-6.3998991	106.8275732	0101000020E6100000F34295F5F6B45A40A1CC50267F9919C0	Tidak ada	4.8	52	3276061	1
228	L' Nuca Molas Coffee	Jl. Margonda No.367. Kemiri Muka. Kota Depok	1	-6.3719283	106.8325713	0101000020E6100000A54522D948B55A40D8D3B3C5DA7C19C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.4	7	3276061	1
229	Cafe 33 Coffee Shop And Resto	Jalan Raya No.12C. Tanah Baru. Kota Depok	1	-6.3718419	106.808523	0101000020E610000015C440D7BEB35A4048217F1FC47C19C0	Kampus / Sekolah	4.4	293	3276061	1
230	Kopi Kenangan - Ruko Raden Sanim Depok	Jl. Raden Sanim No.R5. Tanah Baru. Kota Depok	1	-6.371394	106.8005928	0101000020E6100000705A95E93CB35A40F5B86FB54E7C19C0	Kampus / Sekolah	4.5	79	3276061	1
231	Kylau Common Space	Jl. Palakali No.38. Kukusan. Kota Depok	1	-6.3685457	106.8185838	0101000020E610000044824EAD63B45A406253420B647919C0	Kampus / Sekolah	4.4	518	3276061	1
232	Point Coffee - Kukusan	Jl. Kukusan Raya No.7. RW.9. Kukusan. Kota Depok	1	-6.3657957	106.8137394	0101000020E6100000DE9D6B4E14B45A40D811E225937619C0	Kampus / Sekolah	4.9	185	3276061	1
233	Toko Matcha	Jl. K.H.M. Usman No.81 A. Kukusan. Kota Depok	0	-6.3643077	106.8157577	0101000020E610000074BDC85F35B45A4053B9E4130D7519C0	Kampus / Sekolah	5	372	3276061	1
234	QITA CAFE	Lantai 2 dan Rooftop. Jl. K.H.M. Usman No.38. Kukusan. Kota Depok	1	-6.3598753	106.8167831	0101000020E61000003B9B9F2C46B45A40818D9026837019C0	Kampus / Sekolah	4.4	44	3276061	1
235	Kopi Kenangan - M Kahfi	Jl. Moh. Kahfi 1. RT.7/RW.03. Tanah Baru. Kota Depok	1	-6.3635599	106.8064554	0101000020E6100000B02B1CF79CB35A40528CE20B497419C0	Kampus / Sekolah	4.7	74	3276061	1
236	Kenduri Coffee Depok	Jl. K.H.M. Usman No.161a. Kukusan. Kota Depok	1	-6.3707899	106.8134045	0101000020E6100000D57ABFD10EB45A409ABFF858B07B19C0	Kampus / Sekolah	4.9	49	3276061	1
237	Kopi Kenangan - Apotek Roxy Nusantara Depok (Container)	Apotek Roxy Nusantara Depok (Container. Jl. Nusantara Raya. Beji. Kota Depok	1	-6.3843455	106.8148473	0101000020E6100000F82E4A7526B45A408675E3DD918919C0	Kampus / Sekolah	4	148	3276061	1
238	Sekar Coffee & Eatery	Jl. H. Amat. Kukusan. Kota Depok	0	-6.3595467	106.8208411	0101000020E61000009CED1BA988B45A40F58997022D7019C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.6	56	3276061	1
239	Habitat Milk and Coffee 2.0	Jl. Kramat No.51. RT.02/RW.08. Tanah Baru. Kota Depok	1	-6.3667291	106.8051854	0101000020E6100000DE0D582888B35A404FF74BD5877719C0	Kampus / Sekolah	4.9	50	3276061	1
240	Kedai kopi forji	Jl. Kabel No.01. Kukusan. Kota Depok	1	-6.3649402	106.8211577	0101000020E6100000F39606D98DB45A4099FB3FE2B27519C0	Stasiun / Halte. Mall / Pusat perbelanjaan. Kampus / Sekolah. Perkantoran	4.8	57	3276061	1
\.


--
-- Name: umkm_id_seq; Type: SEQUENCE SET; Schema: umkm; Owner: postgres
--

SELECT pg_catalog.setval('umkm.umkm_id_seq', 240, true);


--
-- Name: umkm umkm_pkey; Type: CONSTRAINT; Schema: umkm; Owner: postgres
--

ALTER TABLE ONLY umkm.umkm
    ADD CONSTRAINT umkm_pkey PRIMARY KEY (id);


--
-- Name: umkm_district_id_fe5d789b; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_district_id_fe5d789b ON umkm.umkm USING btree (district_id);


--
-- Name: umkm_district_idx; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_district_idx ON umkm.umkm USING btree (district_id);


--
-- Name: umkm_jenis_idx; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_jenis_idx ON umkm.umkm USING btree (jenis_umkm_id);


--
-- Name: umkm_jenis_umkm_id_28a4eb1b; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_jenis_umkm_id_28a4eb1b ON umkm.umkm USING btree (jenis_umkm_id);


--
-- Name: umkm_location_b7327388_id; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_location_b7327388_id ON umkm.umkm USING gist (location);


--
-- Name: umkm_nama_idx; Type: INDEX; Schema: umkm; Owner: postgres
--

CREATE INDEX umkm_nama_idx ON umkm.umkm USING btree (nama);


--
-- Name: umkm umkm_district_id_fe5d789b_fk_districts_id; Type: FK CONSTRAINT; Schema: umkm; Owner: postgres
--

ALTER TABLE ONLY umkm.umkm
    ADD CONSTRAINT umkm_district_id_fe5d789b_fk_districts_id FOREIGN KEY (district_id) REFERENCES public.districts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: umkm umkm_jenis_umkm_id_28a4eb1b_fk_jenis_umkm_id; Type: FK CONSTRAINT; Schema: umkm; Owner: postgres
--

ALTER TABLE ONLY umkm.umkm
    ADD CONSTRAINT umkm_jenis_umkm_id_28a4eb1b_fk_jenis_umkm_id FOREIGN KEY (jenis_umkm_id) REFERENCES umkm.jenis_umkm(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

